### ISSUE TITLE
IPv6 Issue

### ISSUE THREAD

**Issue by DuoIncure** [alvin0319/WaterdogExtraInjector#2]
With the IPv6 setting enabled in `server.properties`, you get an error like the following:

https://www.toptal.com/developers/hastebin/ineqidutuj.sql

With the IPv6 setting disabled, the problem does not happen.

**Comment by alvin0319** [comment]
I'll push the updated version which doesn't override raklib interface. I already fixed that issue on my local machine and the pushing changes is remain.
