### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Theslowaja** [alvin0319/WaterdogExtraInjector#9]
[NetworkSession: 127.0.0.1 64595] Bad packet (error ID cfe596bf9f4b): Error processing LoginPacket: JSON property "Waterdog_XUID" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\ClientData

how to fix it?

**Comment by alvin0319** [comment]
You should remove this plugin or enable login_extras on WDPE's config.yml
